---
# file: provisioning_robo_gw_bash.yml
#...............................................................
#   this playbook would
#     - run 'iesoRoboProvisioningDemo_Phase1.sh' on the SMS to
#..............................................................
- hosts: 192.168.100.2
  gather_facts: no
  # connection: local
 
  tasks:
  - name: "Running the provisioning script on 192.168.100.2"
    script: /home/administrator/ieso_robo_provisioning/scripts/iesoRoboProvisioningDemo_Phase1.sh
    register: output
 
  - debug: var=output.stdout_lines
